name: Issue and Label Event Tracker

on:
  issues:
    types: [opened]
  label:
    types: [created]

jobs:
  print_details:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print event details
      run: |
        echo "Event Type: ${{ github.event_name }}"
        echo "Triggered by: ${{ github.actor }}"
        echo "Date and Time: ${{ github.event.created_at }}"
